apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  namespace: recommendation-engine-qa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
        - name: product
          image: 977099024018.dkr.ecr.us-east-1.amazonaws.com/product-service:0.1.5
          ports:
            - containerPort: 5001
          envFrom:
            - secretRef:
                name: recommendation-engine-secrets
