apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: recommendation-engine-prod
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: /
spec:
  selector:
    app: frontend-service
    color: blue
  ports:
    - protocol: TCP
      port: 80 # external port (Ingress will connect to 80)
      targetPort: 3000 # inside container
  type: ClusterIP
