apiVersion: v1
kind: Service
metadata:
  name: recommendation-service
  namespace: recommendation-engine-prod
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: /healthz
spec:
  selector:
    app: recommendation-service
    color: blue
  ports:
    - protocol: TCP
      port: 5002
      targetPort: 5002
  type: ClusterIP
