apiVersion: v1
kind: Secret
metadata:
  name: recommendation-engine-secrets
  namespace: recommendation-engine-prod
type: Opaque
data:
  OPENAI_API_KEY: QUl6YVN5QzVSNlRWNjlQS25vVXNGSklHZHlyTFZ0aVNybHhINkhN
  MODEL_NAME: Z2VtaW5pLTIuMC1mbGFzaA==
  MAX_TOKENS: MTAwMA==
  TEMPERATURE: MC43
  DATA_PATH: ZGF0YS9wcm9kdWN0cy5qc29u
