apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-service-green
  namespace: recommendation-engine-prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend-service
      color: green
  template:
    metadata:
      labels:
        app: frontend-service
        color: green
    spec:
      containers:
        - name: frontend
          image: ''
          ports:
            - containerPort: 3000
