apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service-green
  namespace: recommendation-engine-prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: product-service
      color: green
  template:
    metadata:
      labels:
        app: product-service
        color: green
    spec:
      containers:
      - name: product
        image: 977099024018.dkr.ecr.us-east-1.amazonaws.com/product-service:0.1.4
        ports:
        - containerPort: 5001
        envFrom:
        - secretRef:
            name: recommendation-engine-secrets
