apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-service-blue
  namespace: recommendation-engine-prod
spec:
  replicas: 0
  selector:
    matchLabels:
      app: frontend-service
      color: blue
  template:
    metadata:
      labels:
        app: frontend-service
        color: blue
    spec:
      containers:
        - name: frontend
          image: ''
          ports:
            - containerPort: 3000
