apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-service
  namespace: recommendation-engine-uat
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend-service
  template:
    metadata:
      labels:
        app: frontend-service
    spec:
      containers:
        - name: frontend
          image: ''
          ports:
            - containerPort: 3000
