apiVersion: batch/v1
kind: Job
metadata:
  generateName: trigger-gh-workflow-
  namespace: recommendation-engine-uat
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
      - name: trigger-workflow
        image: curlimages/curl
        env:
        - name: GITHUB_TOKEN
          valueFrom:
            secretKeyRef:
              name: github-token-secret
              key: token
        command:
          - "sh"
          - "-c"
          - |
            curl -X POST \
              https://api.github.com/repos/punnam14/recommendation-engine-infra-repo/dispatches \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer $GITHUB_TOKEN" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              -d '{"event_type":"post-deploy-uat-tests"}'
      restartPolicy: Never
