name: Recommendation - Test, Build & Push

on:
  repository_dispatch:
    types: [build-recommendation]
  schedule:
    - cron: '0 5 * * *'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to tag and push'
        required: true

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      ECR_URI: ${{ secrets.ECR_RECOMMENDATION_URI }}

    steps:
      - name: Clone Source Repository
        run: |
          git clone https://github.com/punnam14/recommendation-engine-microservices.git source

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Install Dependencies
        working-directory: ./source/recommendation-service
        run: pip install -r requirements.txt

      - name: Run Tests
        working-directory: ./source/recommendation-service
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          MODEL_NAME: ${{ secrets.MODEL_NAME }}
          MAX_TOKENS: ${{ secrets.MAX_TOKENS }}
          TEMPERATURE: ${{ secrets.TEMPERATURE }}
          DATA_PATH: ${{ secrets.DATA_PATH }}
        run: PYTHONPATH=. pytest

      - name: Set Version
        run: echo "VERSION=${{ github.event.client_payload.version }}" >> $GITHUB_ENV

      - name: Docker Login to ECR
        run: |
          aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_URI

      - name: Build Docker Image
        working-directory: ./source/recommendation-service
        run: |
          docker build -t recommendation-service .
          docker tag recommendation-service:latest $ECR_URI:${{ env.VERSION }}
          docker tag recommendation-service:latest $ECR_URI:latest

      - name: Push to ECR
        run: |
          docker push $ECR_URI:${{ env.VERSION }}
          docker push $ECR_URI:latest
