name: Run Integration Tests after Deploy

on:
 repository_dispatch:
   types: [post-deploy-tests]

jobs:
 run-tests:
   runs-on: ubuntu-latest

   steps:
     - name: Clone Source Repository
       run: |
         git clone https://github.com/punnam14/recommendation-engine-microservices.git source

     - name: Set Up Python
       uses: actions/setup-python@v4

     - name: Install Test Dependencies
       run: |
         pip install pytest requests

     - name: Run Integration Tests
       working-directory: ./source/tests
       run: |
         pytest --tb=short --disable-warnings
     
     - name: Install jq and yq
       run: |
         sudo apt-get update && sudo apt-get install -y jq
         sudo wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/bin/yq
         sudo chmod +x /usr/bin/yq

     - name: Promote Updated Service to UAT
       run: |
         git clone https://x-access-token:${{ secrets.TOKEN_GITHUB }}@github.com/punnam14/recommendation-engine-infra-repo.git infra-repo
         cd infra-repo

         # Read values from metadata JSON
         SERVICE=$(jq -r '.service' kubernetes/argocd/meta/last-service-updated.json)
         VERSION=$(jq -r '.version' kubernetes/argocd/meta/last-service-updated.json)
         echo "Promoting $SERVICE with version $VERSION to UAT..."

         # Set UAT deployment path
         DEPLOYMENT_FILE="kubernetes/uat/${SERVICE}-deployment.yml"

         # Update image tag in UAT deployment
         yq eval -i '.spec.template.spec.containers[0].image |= sub(":.*$"; ":" + strenv(VERSION))' $DEPLOYMENT_FILE

         # Commit & push
         git config user.name "github-actions[bot]"
         git config user.email "github-actions[bot]@users.noreply.github.com"
         git add $DEPLOYMENT_FILE
         git commit -m "chore: promote $SERVICE to version $VERSION in UAT"
         git push
