name: Run UAT Tests after Deploy

on:
 repository_dispatch:
   types: [post-deploy-uat-tests]

jobs:
 run-tests:
   runs-on: ubuntu-latest

   steps:
     - name: Install jq and yq
       run: |
         sudo apt-get update && sudo apt-get install -y jq
         sudo wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/bin/yq
         sudo chmod +x /usr/bin/yq  

     - name: Fetch Updated Service name and Version 
       run: |
         git clone https://x-access-token:${{ secrets.TOKEN_GITHUB }}@github.com/punnam14/recommendation-engine-infra-repo.git infra-repo
         cd infra-repo

         SERVICE=$(jq -r '.service' kubernetes/argocd/meta/last-service-updated.json)
         VERSION=$(jq -r '.version' kubernetes/argocd/meta/last-service-updated.json)
         echo "SERVICE=$SERVICE" >> $GITHUB_ENV
         echo "VERSION=$VERSION" >> $GITHUB_ENV
     
     - name: Send UAT Completion Notification
       uses: dawidd6/action-send-mail@v3
       with:
         server_address: smtp.ethereal.email
         server_port: 587
         username: ${{ secrets.ETHEREAL_USER }}
         password: ${{ secrets.ETHEREAL_PASS }}
         subject: "✅ UAT Passed - Ready for Prod"
         body: |
           Hi Team,

           Service - ${{ env.SERVICE }} has been upgraded to version - ${{ env.VERSION }} and successfully deployed to the UAT environment.
          
           🔍 You can test it at: https://uat.hottake.pro/

           👉 Once verified, please proceed with production deployment by manually running the following workflow:
           https://github.com/punnam14/recommendation-engine-infra-repo/actions

           UAT Bot
         to: kayden.lindgren43@ethereal.email
         from: "UAT Bot <uat-bot@ethereal.email>"


    